# Generated by Django 5.2.7 on 2025-10-25 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("clinic_type", "Clinic Type"),
                            ("marital_status", "Marital Status"),
                            ("current_status", "Current Status"),
                            ("complication_status", "Complication Status"),
                            ("vaccine_name", "Vaccine Name"),
                            ("special_blood_type", "Special Blood Type"),
                            ("growth", "Growth"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ComplicationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosisType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("icd_code", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DrugName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("does", models.CharField(blank=True, max_length=50, null=True)),
                ("regimen", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvestigationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ThalassemiaUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=150)),
                ("common_name", models.CharField(blank=True, max_length=100, null=True)),
                ("gender", models.CharField(choices=[("M", "Male"), ("F", "Female")], max_length=1)),
                (
                    "ethnicity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Sinhalese", "Sinhalese"),
                            ("Tamil", "Tamil"),
                            ("SriLankanMoor", "Sri Lankan Moor"),
                            ("Burger", "Burger"),
                            ("Other", "Other"),
                        ],
                        default="Sinhalese",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("nic_number", models.CharField(blank=True, max_length=15, null=True)),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("genotype", models.CharField(blank=True, max_length=50, null=True)),
                ("date_of_registration", models.DateField(blank=True, null=True)),
                ("HB_level_at_diagnosis", models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ("diagnosis_date", models.DateField(blank=True, null=True)),
                ("date_first_transfused", models.DateField(blank=True, null=True)),
                ("transfusion_regimen", models.CharField(blank=True, max_length=200, null=True)),
                ("date_iron_chelation_started", models.DateField(blank=True, null=True)),
                ("allergic_history", models.TextField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("contact_number", models.CharField(blank=True, max_length=20, null=True)),
                ("guardian_name_1", models.CharField(blank=True, max_length=100, null=True)),
                ("guardian_name_2", models.CharField(blank=True, max_length=100, null=True)),
                ("guardian_contact_number_1", models.CharField(blank=True, max_length=20, null=True)),
                ("guardian_contact_number_2", models.CharField(blank=True, max_length=20, null=True)),
                ("date_of_transfer", models.DateField(blank=True, null=True)),
                ("date_of_death", models.DateField(blank=True, null=True)),
                ("course_of_death", models.TextField(blank=True, null=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="client_photos/")),
                ("special_note", models.TextField(blank=True, null=True)),
                (
                    "current_status",
                    models.ForeignKey(
                        limit_choices_to={"category": "current_status"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients_current_statuses",
                        to="clients.choice",
                    ),
                ),
                (
                    "marital_status",
                    models.ForeignKey(
                        limit_choices_to={"category": "marital_status"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients_marital_statuses",
                        to="clients.choice",
                    ),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients_diagnosis",
                        to="clients.diagnosistype",
                    ),
                ),
                (
                    "transferred_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients_transferred_units",
                        to="clients.thalassemiaunit",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients_units",
                        to="clients.thalassemiaunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_of_admission", models.DateField()),
                ("reason_for_admission", models.TextField(default="Blood Transfusion")),
                ("date_of_discharge", models.DateField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="admissions", to="clients.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClinicVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_visit", models.DateField()),
                ("problem", models.TextField(blank=True, null=True)),
                ("action", models.TextField(blank=True, null=True)),
                ("referral", models.CharField(blank=True, max_length=200, null=True)),
                ("next_visit_date", models.DateField(blank=True, null=True)),
                ("doctor_name", models.CharField(blank=True, max_length=100, null=True)),
                ("follow_up_needed", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="clinic_visits", to="clients.client"
                    ),
                ),
                (
                    "clinic_type",
                    models.ForeignKey(
                        limit_choices_to={"category": "clinic_type"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.choice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Complication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("detected_date", models.DateField()),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="complications", to="clients.client"
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        limit_choices_to={"category": "complication_status"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.choice",
                    ),
                ),
                (
                    "complication",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="clients.complicationtype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_prescribed", models.DateField()),
                ("dose", models.CharField(max_length=50)),
                ("regimen", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=50)),
                ("indication", models.CharField(blank=True, max_length=200, null=True)),
                ("prescribed_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="drugs", to="clients.client"
                    ),
                ),
                (
                    "drug_name",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="clients.drugname"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("Father", "Father"),
                            ("Mother", "Mother"),
                            ("Sibling", "Sibling"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("birth_day", models.DateField(blank=True, null=True)),
                ("pt_id", models.CharField(blank=True, max_length=20, null=True)),
                ("is_carrier", models.BooleanField(default=False)),
                ("contact_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="family_members", to="clients.client"
                    ),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="clients.diagnosistype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GrowthRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_measured", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=6)),
                ("percentile", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="growth_records", to="clients.client"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        limit_choices_to={"category": "growth"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.choice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Investigation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_done", models.DateField()),
                ("value", models.CharField(blank=True, max_length=100, null=True)),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                ("laboratory_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="investigations", to="clients.client"
                    ),
                ),
                (
                    "investigation_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.investigationtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfusion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_of_transfusion", models.DateField()),
                (
                    "HB_level_to_be_kept",
                    models.DecimalField(blank=True, decimal_places=1, default=9.0, max_digits=4, null=True),
                ),
                ("HB_level", models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ("WBC_count", models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ("platelet_count", models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ("amount_of_blood", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("next_date_given", models.DateField(blank=True, null=True)),
                ("reaction", models.CharField(blank=True, default="None", max_length=200, null=True)),
                ("checked_by", models.CharField(blank=True, max_length=100, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transfusions", to="clients.admission"
                    ),
                ),
                (
                    "special_type",
                    models.ForeignKey(
                        limit_choices_to={"category": "special_blood_type"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.choice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_given", models.DateField()),
                ("next_dose_date", models.DateField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="vaccinations", to="clients.client"
                    ),
                ),
                (
                    "vaccine_name",
                    models.ForeignKey(
                        limit_choices_to={"category": "vaccine_name"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.choice",
                    ),
                ),
            ],
        ),
    ]
