# Generated by Django 5.2.7 on 2025-12-19 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfusion",
            name="special_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "special_blood_type"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.choice",
            ),
        ),
    ]
