ROLE_PERMISSIONS = {
    "unit_data_entry": [
        "clients.view_client",
        "clients.add_client",
        "clients.change_client",
        "clients.view_admission",
        "clients.add_admission",
        "clients.change_admission",
        "clients.view_transfusion",
        "clients.view_investigation",
    ],
    "unit_clinician": [
        "clients.view_client",
        "clients.change_client",
        "clients.view_admission",
        "clients.add_admission",
        "clients.change_admission",
        "clients.view_transfusion",
        "clients.add_transfusion",
        "clients.change_transfusion",
        "clients.view_investigation",
        "clients.add_investigation",
        "clients.change_investigation",
    ],
    "unit_admin": [
        "clients.view_client",
        "clients.add_client",
        "clients.change_client",
        "clients.delete_client",
        "clients.view_admission",
        "clients.add_admission",
        "clients.change_admission",
        "clients.delete_admission",
        "clients.view_transfusion",
        "clients.add_transfusion",
        "clients.change_transfusion",
        "clients.delete_transfusion",
        "clients.view_investigation",
        "clients.add_investigation",
        "clients.change_investigation",
        "clients.delete_investigation",
    ],
}
